# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57facdef735604031dc355808521b01be4dc32fee7f1b30faf6e5ac8b8e49e467abc2a3b6bb95a7319b23df5af30ea5ed883e6c70368ba08413c786fbaed8f6e

test:
  secret_key_base: 042cc6e328bd96007e206020d8cad080ad00cd9d34d0a47f75e19145408ee443e4941f21c57bca7ac4d32c24a3ab7d5101f43de7cad6be0ff0be9438dc947772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
